### ISSUE TITLE
Custom delimiter

### ISSUE THREAD

**Issue by rudolf9** [bingo347/sql-require#1]
Hi Dmitriy 

The sql-require is very helpful for my project, many thanks.
I have multiline INSERT statements with semicolon in data.
Can be added functionality to set the custom delimiter?
For example that I could change delimiter to ";--". 
With custom delimiter all works fine for me
and still I can copy and paste data to some SQL client.
Yes, disadvantage is, that I need edit SQL file and append to each line "--".

Rudolf M.

**Comment by bingo347** [comment]
Hi Rudolf

My library support DELIMITER statement in SQL code, you can read about it here: https://dev.mysql.com/doc/refman/8.0/en/stored-programs-defining.html

Does this solve your problem?
